### PR TITLE
WIP ProgramChange support

### PR DESCRIPTION
**Pull request by bilenkonito**
Implemented multichanel support into BardPlayDevice.
Implemented WIP ProgramChange support.
Improved the parsing of auto filename transposing/switching.

### CODE REVIEW

**Comment by bilenkonito** [comment]
I've been using the feature regularly for a few days and haven't found any issues so far.
Ideally I would like to allow the user to disable certain channels to allow for one MIDI device to feed several game instances but I don't think I will have time so I'm submitting the PR as is for now.

**Comment by akira0245** [comment]
Thank you for PR! The guitar tone switching works great, I'll release this in next update :D

**Comment by akira0245** [comment]
@bilenkonito  Sorry for changing your code this much, i found i was not fully understand the way program change works with channels, do you think each midi track should has it's own 16 channel states, or the channel states should keep belongs to bard play device in current way?

**Comment by bilenkonito** [comment]
No worries, I like the latest changes and refactoring.

I think the channels should be part of the virtual output device that interfaces with the game, while tracks should be part of the MIDI file handling logic.
General MIDI doesn't really have a well defined concept of tracks, it's something that MIDI files support for organisation but physical MIDI devices generally don't handle track information beyond maybe the track name event for display purposes like some keyboards with built-in screens do.
The reason why I decided to use a basic channel implementation is that theoretically events from any channel can affect any other channel. Although it's common for BMP adapted files to use track 0 for all events, it's helpful when using regular MIDI files that haven't been adapted.
It also helps avoiding edge cases like MIDI splitters where some channels are provided by one device and other channels by a different one. This used to be a pretty common setup before software synths took over in order to mix base percussion with MIDI instruments using only one MIDI input.

Ideally I think you should also be able to toggle individual channels as that would allow you to use a single MIDI input device to control multiple MidiBard instances.
I've been researching the game's metronome agent a bit lately trying to find a way to trigger the ensemble mode ready check without resorting to firing the Atk event manually and I believe those two features would complement each other pretty well for multibox performances.

On the topic of MIDI input devices, I've recently noticed that non-note events don't seem to be process while using a MIDI input but I've yet to investigate further.

**Comment by akira0245** [comment]
Thanks for the explanation! functions related to start ensemble ready check should be in the latest playlib.dll.
> use a single MIDI input device to control multiple MidiBard instances.     

I tried this before with a virtual midi input device, the results i got is when an input device is been listening by a Midibard instance it can't be listening by another... i had to use midi routers to copy a device's output to multiple virtual devices to make it work, probably I didn't set it up properly.

**Pull request merged**
